Add Python installation guide and Cotainr documentation
Lumi-supercomputer/lumi-userguide pull request #127
Opened 2023-08-25 10:16 UTC by Chroxvi

The main part of this PR is:
- Adding a new page on "Installing Python packages" on LUMI, giving an overview of recommended and discouraged options for installing Python packages on LUMI. This is includes a condensed version of the content in the stale #24. The intention is to close #24 as superseded by this PR.
- Updating the existing documentation on pulling and building Singularity/Apptainer containers on LUMI to include a description of the use of [cotainr](https://cotainr.readthedocs.io/en/stable/) to build containers on LUMI (primarily for Conda/pip environments).
- Updating the "container wrapper" documentation to reflect the more general purpose nature of the tool - not just a Conda/pip wrapper. This includes a tentative change of its name to "Tykky installation wrapper" - please suggest a better name, if you have one! See #110 for more discussion about the motivation for this change.

Additionally, this PR also includes:
- Minor changes and clean-ups to various pages throughout the documentation mentioning do's and don'ts related to Conda, pip, or Python. These now link to the new "Installing Python packages" page.
- A fix for #60 

Open questions:
- [ ] Is "Tykky installation wrapper" the right new name for what is currently known as the "LUMI container wrapper".
- [ ] If we rename the "LUMI container wrapper" in the docs, how do we handle the transition of the [lumi-container-wrapper](https://lumi-supercomputer.github.io/LUMI-EasyBuild-docs/l/lumi-container-wrapper/) module to a new name?

2023-08-28 17:22 UTC, hdrei requested changes
The main change suggestions that I see are:
 - The overview page could give a short description of the Python packages section also as "one way to install software" (or how to formulate it), to have the section structure consistent (as Python packages is placed under Installing software with EasyBuild, Spack and Tykky). 
 - The Python packages section: The listing of the ways to install could be somewhat clearer. Now one needs to use much extra focus to find the different possibilities to install (without reading all the text), or that's my experience at least. A suggestion: Change the headings from how recommended the methods are to the methods themselves? If the methods would be listed as headings, they would also appear on the upper right corner of the page as a list of contents

2023-08-28 17:22 UTC, hdrei commented on docs/software/packages/pytorch.md
> +[python-install]: ./python.md
```suggestion
[python-install]: ./installing/python.md
```

2023-08-28 17:22 UTC, hdrei commented on docs/software/packages/pytorch.md
> +[python-install]: ./python.md
Not sure if this is the way to correct the link. But the previous one didn't work at least

2023-08-28 17:22 UTC, hdrei commented on docs/software/packages/pytorch.md
> +PyTorch can be installed by following the [official instructions](https://pytorch.org/get-started/locally/) for installing a ROCm compatible PyTorch via pip. Please consults the [Python packages inst
```suggestion
PyTorch can be installed by following the [official instructions](https://pytorch.org/get-started/locally/) for installing a ROCm compatible PyTorch via pip. Please consult the [Python packages installation guide][python-install] for an overview of recommended ways to manage pip installations on LUMI. Alternatively, the container images provided by [AMD on DockerHub](https://hub.docker.com/u/rocm) may be used on LUMI.
```

2023-08-28 17:22 UTC, hdrei commented on docs/software/packages/pytorch.md
> +[containers]: ./singularity.md
```suggestion
[containers]: ./containers/singularity.md
```

2023-08-28 17:22 UTC, hdrei commented on docs/software/packages/pytorch.md
> +[containers]: ./singularity.md
Not sure if this fixes the link. But the previous link was broken at least

2023-08-28 17:22 UTC, hdrei commented on docs/software/packages/pytorch.md
> +The communication between LUMI's GPUs during training with Pytorch is done via [RCCL](https://github.com/ROCmSoftwarePlatform/rccl), which is a library of  collective communication routines for AMD G
Is there a reason why the `Slingshot 11 interconnect` link is to HPE docs and not to the page in our docs? Maybe this could link to our docs, and the Network and interconnect page in our docs to the HPE docs?

2023-08-28 17:22 UTC, hdrei commented on docs/software/index.md
```suggestion
[install-policy]: ./policy.md

```

2023-08-28 17:22 UTC, hdrei commented on docs/software/index.md
> +software. This is further explained on the [Install policy](/software/policy/)
```suggestion
software. This is further explained on the [Install policy][install-policy]
```

2023-08-28 17:22 UTC, hdrei commented on docs/software/index.md
> +software. This is further explained on the [Install policy](/software/policy/)
The link was broken and trying to fix it...

2023-08-28 17:22 UTC, hdrei commented on docs/software/containers/singularity.md
> +1. Use [cotainr][cotainr] to build containers on LUMI (only for certain [use
```suggestion
**1. Use [cotainr][cotainr-chapter] tool to build containers on LUMI (only for certain use cases).**
```

2023-08-28 17:22 UTC, hdrei commented on docs/software/containers/singularity.md
> +   cases][cotainr-usecases]).
```suggestion
```

2023-08-28 17:22 UTC, hdrei commented on docs/software/containers/singularity.md
> +2. Build your own container on your local hardware, e.g. your laptop.
```suggestion
**2. [Build your own container][building-local] on your local hardware, e.g. your laptop.**
```

2023-08-28 17:22 UTC, hdrei commented on docs/software/containers/singularity.md
```suggestion
[cotainr-chapter]: ./singularity.md#building-containers-using-cotainr
[building-local]: ./singularity.md#building-containers-on-local-hardware


```

2023-08-28 17:22 UTC, hdrei commented on docs/software/containers/singularity.md
> +### Building containers using cotainr
```suggestion
### Building containers using cotainr tool
```

2023-08-28 17:22 UTC, hdrei commented on docs/software/containers/singularity.md
> +examples][cotainr-lumi-examples] for more details.
This link gives a '404 page not found'

2023-08-28 17:22 UTC, hdrei commented on docs/software/containers/singularity.md
This example needs to be updated! Maybe not the task of this PR, but it doesn't work any more. Should it be a separate issue of should we/someone try to fix it?

2023-08-28 17:22 UTC, hdrei commented on docs/software/installing/python.md
> +i.e. of a lot of small files containing Python code, e.g. a typical
```suggestion
i.e. a lot of small files containing Python code. A typical
```

2023-08-28 17:22 UTC, hdrei commented on docs/software/installing/python.md
> +### Conditionally recommended
```suggestion
### Recommended in certain use cases
```

2023-08-28 17:22 UTC, hdrei commented on docs/software/installing/python.md
> +  Team (LUST).
```suggestion
```

2023-08-28 17:22 UTC, hdrei commented on docs/software/installing/python.md
> +  Team (LUST).
I don't see the point listing this here. Local software collections should be talked about in the overview page of this section, as other software and/or installation methods. Or am I missing a point here why this was added...

2023-08-28 17:22 UTC, hdrei commented on docs/software/installing/python.md
> +strongly discouraged**.
```suggestion
**We strongly discourage using these methods on LUMI**.
```

2023-08-28 17:22 UTC, hdrei commented on docs/software/installing/python.md
> +strongly discouraged**.
I think it shouldn't say something as: "Well, this can be done, but we advice against it" type of thing. It doesn't sound serious enough at least to me. If I would be an inpatient person not willing to learn the methods described above, I would just do the "not recommended" way, if it sounds it is not that seriously discouraged

2023-08-28 17:22 UTC, hdrei commented on docs/software/installing/python.md
> +### Conditionally recommended
"Conditionally" sounds like that "these might not be recommended" and a reader might skip them and not notice that they are actually easy options for certain use cases

2023-08-28 17:22 UTC, hdrei commented on docs/software/installing/python.md
> +### Conditionally recommended
In general I think that it might be better to not put the headings "recommended" and "conditionally recommended" (or something), but rather list the different methods as headings. That way they would also appear in the listing on the upper right corner of the page. I'm not sure how to formulate this change, though, at least right away

2023-08-28 17:22 UTC, hdrei commented on docs/software/installing/container-wrapper.md
> +The [Tykky][tykky-github] installation wrapper (formerly the "LUMI container
```suggestion
The [Tykky][tykky-github] installation wrapper (formerly called the "LUMI container
```

2023-08-28 17:22 UTC, hdrei commented on docs/software/index.md
> +On this page you find guidance on ways to install additional software on LUMI.
```suggestion
On this page you find information of the pre-installed software on LUMI, and guidance on ways to install additional software yourself.
```

2023-08-28 17:22 UTC, hdrei commented on docs/software/index.md
```suggestion

## Pre-installed software on LUMI
- **Software already installed in the LUMI Software Library**: The [LUMI
software library](https://lumi-supercomputer.github.io/LUMI-EasyBuild-docs/)
contains an overview with all software that is installed in the software stacks
available through the LUMI modules and the CrayEnv module (apart from the
documentation of the HPE Cray Programming Environment). For software installed
on the system the first channel to get help on a specific module is through the
`module help` command, but the LUMI Software Library pages sometimes contain
more information on how to run the software, or more information about specific
options that were chosen when installing the software on LUMI.
- **Local software collections**: There are also software available on LUMI installed by local LUMI organizations. These are available for all LUMI users and are updated and supported by the local LUMI organizations themselves, not by LUST.
    * [CSC installed software collection](https://docs.lumi-supercomputer.eu/software/local/csc/)

```

2023-08-28 17:22 UTC, hdrei commented on docs/software/index.md
Would this suit here? The text would need to be formulated a bit more, but I think it might be a good idea to list first the options where a user doesn't need to install anything, and how to find the pre-installes software

2023-08-28 17:22 UTC, hdrei commented on docs/software/index.md
> +- **Use local software collections**: There are also software available on LUMI installed by local LUMI organizations. These are available for all LUMI users and are updated and supported by the loca
```suggestion
As an alternative to installing software yourself, you may:

- **Use an Apptainer/Singularity container**: You can bring a
[Singularity/Apptainer software container][singularity-container] and run it
using the [Singularity container runtime][singularity-jobs] provided by LUMI.

```

2023-08-28 17:22 UTC, hdrei commented on docs/software/index.md
> +    * [CSC installed software collection](https://docs.lumi-supercomputer.eu/software/local/csc/)
```suggestion

```

2023-08-28 17:22 UTC, hdrei commented on docs/software/index.md
> +     large parallel file systems.
I kind of like the previous description because it lists some use cases, and doesn't mention containers. Containers sound scary to someone who has not been using them, and in Tykky case one doesn't need to care about the whole container thing to be able to use the tool accordingly

2023-08-28 17:22 UTC, hdrei commented on docs/software/index.md
> +
Not sure where to place this comment (because can't comment the unmodified part of the page), but below the 'Installing software' heading it says: "We offer three options to install software on LUMI", which is a bit conflicting taking account that on the 'Python packages' page there are described many methods more, although valid for certain use cases only.
In general, the section 'Python packages' should be mentioned on this page also elsewhere than in the warning box in the beginning of the page. For consistency of this section it would make sense to list it similarly than EasyBuild, Spack and Tykky

2023-08-28 17:22 UTC, hdrei commented on docs/software/installing/container-wrapper.md
> +    For some use cases, Tykky is an excellent tools for managing Conda/pip
```suggestion
    For some use cases, Tykky is an excellent tool for managing Conda/pip
```

2023-08-28 17:22 UTC, hdrei commented on docs/software/index.md
> +     large parallel file systems.
Ok, the previous comment is maybe unnecessary, since I see that the previous description was maybe misleading...

2023-08-30 07:11 UTC, Chroxvi commented on docs/software/containers/singularity.md
> +examples][cotainr-lumi-examples] for more details.
I fixed the link, which was missing an "I" in the end. The correct link is: https://github.com/DeiC-HPC/cotainr/tree/main/examples/LUMI

2023-08-30 07:14 UTC, Chroxvi commented on docs/software/containers/singularity.md
I would prefer to keep such an update in a separate PR as it doesn't really have anything to do with either Python or cotainr. So yes, I think we should create an issue detailing what doesn't work. Then someone should fix it in a separate PR. Also this reminds me that we need to determine a strategy for keeping such examples in the docs up-to-date...

2023-08-30 08:30 UTC, Chroxvi commented on docs/software/installing/python.md
> +  Team (LUST).
This is mainly to point out that if you are used to e.g. `module load pytorch` on one of the Finish HPC systems, you have a similar option on LUMI, i.e. you might not need to install anything yourself. I will try to make this point more clear.

2023-08-30 08:34 UTC, Chroxvi commented on docs/software/packages/pytorch.md
> +The communication between LUMI's GPUs during training with Pytorch is done via [RCCL](https://github.com/ROCmSoftwarePlatform/rccl), which is a library of  collective communication routines for AMD G
Maybe the "Network and interconnect" page didn't exist when this was written?

I like your suggestion, so I will include it, though it probably belongs in another PR...

2023-08-30 08:42 UTC, Chroxvi commented on docs/software/index.md
> +     large parallel file systems.
I have significantly reworked the software overview page. Does this new version address your concern?

2023-08-30 08:42 UTC, Chroxvi commented on docs/software/index.md
> +
I have significantly reworked the software overview page. Does this new version address your concern?

2023-08-30 08:49 UTC, Chroxvi commented
@hdrei I have updated the PR to address your review comments. Please see check if all your concerns have been address.

- I have done a major rework of the software overview page. I like the new version a lot, but I am also a bit concerned about the overlap with the content in https://docs.lumi-supercomputer.eu/runjobs/lumi_env/Lmod_modules/ and https://docs.lumi-supercomputer.eu/runjobs/lumi_env/softwarestacks/.
- I have changed the structure of the Python packages installation page to more aggressively make use of sections as you suggested. I like the change. Initially, I also thought about creating a table as an alternative. However, I felt it would probably be difficult to make it easily comprehensible given the somewhat limited formatting options, markdown files provide.

2023-09-04 12:44 UTC, Danzelot approved these changes

2023-09-07 17:11 UTC, hdrei requested changes
This starts to look very good, I think. I made some small corrections/comments, and some small change suggestions

2023-09-07 17:11 UTC, hdrei commented on docs/software/containers/singularity.md
> +    environment to make sure they fit the hardware in LUMI. It simply installs
```suggestion
    environment to make sure they fit the hardware of LUMI. It simply installs
```

2023-09-07 17:11 UTC, hdrei commented on docs/software/containers/singularity.md
> +```
The example given is not exactly "running a container job"? I'm not sure what/if to change here, and the link to LUMI examples in github kind of fixes this confusement

2023-09-07 17:11 UTC, hdrei commented on docs/software/containers/singularity.md
Ok, I made a note about this

2023-09-07 17:11 UTC, hdrei commented on docs/software/index.md
> +guidance on ways to install additional software yourself. If you are
```suggestion
On this page you find information about pre-installed software on LUMI as well as guidance on ways to install additional software yourself. If you are
```

2023-09-07 17:11 UTC, hdrei commented on docs/software/index.md
> +Please note that the LUMI User Support Team can only offer limited help with
```suggestion
Please note that LUMI User Support Team can only offer limited help with
```

2023-09-07 17:11 UTC, hdrei commented on docs/software/index.md
> +    ][python-install] for en overview of options for installing Conda/pip
```suggestion
    ][python-install] for an overview of options for installing Conda/pip
```

2023-09-07 17:11 UTC, hdrei commented on docs/software/index.md
> +    were chosen when installing the software on LUMI.
```suggestion
    A full overview of software, that is either pre-installed in the [LUMI software
    stacks][software-stacks], or available as a user-installable LUMI-specific build recipe for the
    [EasyBuild][easybuild] package manager, can be found in the [LUMI software
    library][software-library]. The information, if a software is pre-installed or user-installable, can be found when you open the page of the specific software. For software installed in the
    [central LUMI software stacks][software-stacks], the first channel to get
    help on a specific module is through the `module help` command, but the LUMI
    [Software Library pages][software-library] sometimes contain more information
    on how to run the software, or more information about specific options that
    were chosen when installing the software on LUMI. Consult the [module environment page][module-env] for instructions on identifying the pre-installed software on LUMI through the module system instead.
    Read more about the user-installable software with EasyBuild in the [next section](#installing-additional-software). 
```

2023-09-07 17:11 UTC, hdrei commented on docs/software/index.md
> +    There is also pre-installed software available on LUMI provided by local LUMI
```suggestion
    There is also pre-installed software available provided by local LUMI
```

2023-09-07 17:11 UTC, hdrei commented on docs/software/index.md
> +- Local software collections
```suggestion
- Software collections by local organizations
```

2023-09-07 17:11 UTC, hdrei commented on docs/software/index.md
>      Consult the [module environment page][module-env] for instructions on
```suggestion

```

2023-09-07 17:11 UTC, hdrei commented on docs/software/index.md
> +    identifying the already available software on LUMI through the module system instead.
```suggestion

```

2023-09-07 17:11 UTC, hdrei commented on docs/software/index.md
```suggestion
```

2023-09-07 17:11 UTC, hdrei commented on docs/software/index.md
I'd like to replace the above lines with the following (but the website version doesn't let me). This adds the word "pre-installed", but is otherwise the same text:

An overview of (almost) all software that we provide pre-installed in the central software stack or for which we provide ready-to-use EasyBuild build recipes for a user installation can be found in the [LUMI Software Library][software-library].

2023-09-07 17:11 UTC, hdrei commented on docs/software/index.md
> +
Yes, it's much better now!

2023-09-07 17:11 UTC, hdrei commented on docs/software/installing/python.md
> +them from multiple processes at the same time, puts a lot of strain on the
```suggestion
them by multiple processes at the same time, puts a lot of strain on the
```

2023-09-07 17:11 UTC, hdrei commented on docs/software/installing/python.md
> +[Lustre file system][lustre] serving these storage locations. Lustre simple
```suggestion
[Lustre file system][lustre] serving these storage locations. Lustre simply
```

2023-09-07 17:11 UTC, hdrei commented on docs/software/installing/python.md
> +    This is an quite old Python installation (version 3.6) without any Scientific
```suggestion
    This is quite an old Python installation (version 3.6) without any Scientific
```

2023-09-07 17:11 UTC, hdrei commented on docs/software/installing/python.md
> +of installing directly to the file systems. Using a container solves the "many
```suggestion
containers][singularity-containers] for managing Python installations. Using a container solves the "many
```

2023-09-07 17:11 UTC, hdrei commented on docs/software/installing/python.md
> +Python environments at the same time. You may either [use an existing
```suggestion
Python environments at the same time. To use a container, you may either [use an existing
```

2023-09-07 17:11 UTC, hdrei commented on docs/software/installing/python.md
> +of installing directly to the file systems. Using a container solves the "many
I'm trying to make the text sound like "the generally recommended installation methods" are not the only ones that are possible to use. (This becomes clear when one reads further to the next block "Installation methods recommended for specific use cases", or course.)

2023-09-07 17:11 UTC, hdrei commented on docs/software/installing/python.md
> +software stacks provided on the Finish HPC systems, which contains some Python
```suggestion
software stacks provided on the Finnish HPC systems, which contains some Python
```

2023-09-07 17:11 UTC, hdrei commented on docs/software/installing/python.md
> +[CSC provides a software stack][csc-software-stack] on LUMI, similar to the
```suggestion
[CSC provides a small additional software stack][csc-software-stack] on LUMI, similar to the
```

2023-09-07 17:11 UTC, hdrei commented on docs/software/installing/container-wrapper.md
> +In order to wrap a basic [Conda][conda] installation, create an `<install_dir>`
```suggestion
In order to wrap a basic [Conda][conda] installation, create an installation directory
```

2023-09-08 08:40 UTC, Chroxvi commented on docs/software/containers/singularity.md
> +```
Maybe just change `--version` to `my_script.py` and mention that `my_script.py` is your Python script?

2023-09-08 08:56 UTC, Chroxvi commented on docs/software/index.md
I will push this change manually.

2023-09-08 09:11 UTC, Chroxvi commented
@Nortamo, this PR makes some changes to the description of Tykky in the LUMI docs. Please chime in if you think some of it is inaccurate or otherwise needs to be changed.

2023-09-18 07:08 UTC, Nortamo commented
> @Nortamo, this PR makes some changes to the description of Tykky in the LUMI docs. Please chime in if you think some of it is inaccurate or otherwise needs to be changed.

Hi,
Sorry for the late reply I was away a week. 
Changes a look good to me. New name is also sensible. Great work!

2023-09-18 07:10 UTC, Chroxvi commented
@Nortamo No problem! Thanks a lot for taking your time to look at this.

2023-09-20 05:50 UTC, hdrei approved these changes

2023-09-22 06:12 UTC, merged